"use strict";

const germanLanguage = {
    es: "ES",
    placeholder1: "K",
    ist: "IST",
    placeholder2: "L",
    minutenFuenf: "FÜNF",
    minutenZehn: "ZEHN",
    minutenZwanzig: "ZWANZIG",
    minutenDrei: "DREI",
    minutenViertel: "VIERTEL",
    nach: "NACH",
    placeholder3: "WIFI",
    vor: "VOR",
    halb: "HALB",
    placeholder4: "OK",
    zwoelf: "ZWÖLF",
    zwei: "ZWEI",
    ein: "!E!IN",
    eins: "!E!I!NS",
    sieben: "!SIEBEN",
    placeholder5: "ERR",
    drei: "DREI",
    fuenf: "FÜNF",
    elf: "ELF",
    vier: "VIER",
    neun: "NEUN",
    zehn: "ZEHN",
    acht: "ACHT",
    placeholder6: "RHO",
    placeholder7: "TEC",
    sechs: "SECHS",
    uhr: "UHR"
}

const englishLanguage = {
    it: "IT",
    placeholder1: "L",
    is: "IS",
    placeholder2: "AS",
    am: "AM",
    pm: "PM",
    placeholder3: "AC",
    minutesQuarter: "QUARTER",
    placeholder4: "DC",
    minutesTwenty: "TWENTY",
    minutesTwentyFive: "!T!W!E!N!T!YFIVE",
    minutesFive: "!F!I!V!E",
    placeholder5: "X",
    half: "HALF",
    placeholder6: "S",
    minuesTen: "TEN",
    placeholder7: "F",
    to: "TO",
    past: "PAST",
    placeholder8: "ERU",
    nine: "NINE",
    one: "ONE",
    six: "SIX",
    three: "THREE",
    four: "FOUR",
    five: "FIVE",
    two: "TWO",
    eight: "EIGHT",
    eleven: "ELEVEN",
    seven: "SEVEN",
    twelve: "TWELVE",
    ten: "TEN",
    placeholder9: "SE",
    clock: "OCLOCK"
}

var germanHoursWords = ["ein", "zwei", "drei", "vier", "fuenf", "sechs", "sieben", "acht", "neun", "zehn", "elf", "zwoelf"];
var englishHoursWords= ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve"];
